spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: yaelrmz@sandbox61950471d54f49b1af2de92ff7156c90.mailgun.org

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

chirp:
  email:
    url: "http://chirp.pl-coding.com"
  rate-limit:
    ip:
      applyLimit: true
